### ISSUE TITLE
Blog post?

### ISSUE THREAD

**Issue by pablobernabeu** [anenadic/research-sustainability-storyboard#5]
Hi all,

I've been thinking that our hack day provides a great opportunity for a blog post--doesn't it? Would anyone be in for this? Just by writing out the content we put forward, I think that a lovely blog post could pop up. I could write and pass around a first draft.

No pressure, though, of course :)

**Comment by 3mmaRand** [comment]
Hi Pablo,
Nice idea. It might be incorporated in to the blog from a day 1 discussion group - have a look at Group J - How can RSEs and similar educate and engage with busy PIs regarding software sustainability? 
Perhaps the blog could describe the development of an idea through the three day workshop?

**Comment by pablobernabeu** [comment]
Hi Emma,

Thank you--that sounds great to me. I'll draft something to fit the context and put in a suggestion in the Group J doc.
